####################################################################################
# Script: txt_to_csv.R
# Author: Wenting Lyu
# Notes: this script helps transform the txt file to cxv file for later analysis.
#         please note that there are two ways to run the script.
#         1) interactive way. 
#         First, run script in console by typing: source("txt_to_csv.R") 
#         Second, select the txt file generated by lipidSearch from the poping window
#         Third, input the name for storing the uncleaned data, e.g. "uncleanedData.csv"
#         2) straight way.
#         First comment the interactive way by selecting the interactive block in the code 
#               (comment shortcut: command+shift+c)
#         Second rewrite the last line of code write_csv(., name) by changing the name variable 
#               to the name you want, e.g. "uncleanedData.csv"
#         Third run the code line by line or as a whole
#####################################################################################
rm(list=ls())

list.of.packages <- c("tidyverse", "readr", "magrittr")
need.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if(length(need.packages)) install.packages(need.packages)

#######################
# Required library
library("tidyverse")
library("readr")
library("magrittr")
#######################

 
# input the original txt file and read by lines
file.lines <- read_lines(file.choose(), skip_empty_rows=TRUE)

# Find row containing sample and result
sample.index <- grepl("Sample", file.lines) %>% which(.==TRUE)
header.index <- grepl("Result", file.lines) %>% which(.==TRUE)

# Get the sample size and replicate
sample.neg <- length(grepl("neg", file.lines[sample.index:header.index]) %>% which(.==TRUE))
sample.pos <- length(grepl("pos", file.lines[sample.index:header.index]) %>% which(.==TRUE))

# simple way if the neg and positive tests are equal
size <- (header.index-sample.index-1)/2

# Verify the sample size info are correct.
message("Reminder: Is your sample negative tests are ", sample.neg, " times?")
message("Reminder: Is your sample positive tests are ", sample.pos, " times?")


# header.index <- grepl("Result", file.lines) %>% which(.==TRUE)

# get the result data and transform into data frame.
uncleaned.data <- file.lines %>% 
                 as.data.frame(., stringsAsFactors=FALSE) %>% 
                 slice((header.index+1):length(file.lines))
  
# substract the frist row and store it as colnames
col.names <- unlist(strsplit(as.character(uncleaned.data[1,]), split="\t"))

# reconstruct the data columns and store it into the file
####################################################################################
# Interactive way to generating file by just typing the command: "source("txt_to_csv.R")", 

message("Please input the name for the uncleaned data, e.g. uncleanedData.csv")
name <- readline("File name: ")

####################################################################################
raw.data<- uncleaned.data %>% 
          slice(-1) %>% 
          separate(., 1, into=col.names, sep="\t") 

# selecting the columns we want for analysis
cols.data <- raw.data %>%
            select(contains("ARatio"), contains("APValue"), 
                   contains("MainGrade"), contains("MainArea"),
                   -contains("NMA"), -contains("Score")
                   )
unorder.name <- paste("unordered.", name, sep="")
#### unordered data            
uncleaned.data <- raw.data %>% select(1:9) %>% bind_cols(cols.data) %>% write_csv(., unorder.name)

#### ordered ones 
order.sample.names <- uncleaned.data %>% 
                      select(matches("\\[(c|s.*)\\]")) %>%    
                      colnames() %>% 
                      str_sort(., numeric=TRUE) 

unorder.data <- uncleaned.data[-which(names(uncleaned.data) %in% order.sample.names)]

order.data <- uncleaned.data[,order.sample.names] %>% 
              bind_cols(unorder.data, .) %>%
              arrange(Class, LipidMolec) %>% 
              write_csv(., name)
