####################################################################################
# Script: Laura.fa.r
# Author: Wenting Lyu
# Notes: This script helps calculate the 
#        SFA, MUFA, PUFA and the aggregated main area for each sample.
#       First, Make sure that your R and Rstudio are newly enough for installing the 
#             packages needed in the script. Otherwise the script will pop out warnings 
#             for packages and won't run.
#       Second, click the "Laura.project.Rproj" 
#       Third, to run the script, please type the command below in the console:
#                 source("Laura.fa.r")   
#              or, click the button "source"
#         
#####################################################################################
rm(list=ls())

list.of.packages <- c("BiocManager","tidyverse", "readr", "magrittr")
need.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if(length(need.packages)) install.packages(need.packages)

#######################
# Required library
library("tidyverse")
library("readr")
library("magrittr")
#######################
#########################################################################################
message("Please run script txt_to_csv.R for converting original file from LipidSearch to get standard file for analysis. \n If you already have file generated by this script, you can continue. ")

############################################################################################ 
# filter data 
# Read in file, and store the data 
lipidomics <- read_csv(file.choose("Please open the standard file generated from txt_to_csv.R"), col_types = cols())

# select and count the sample grades you want, filter the p value which less than 0.001
# this step extract the needed sample information from the file automatically
lipidCount <- lipidomics %>% 
  select(contains("Grade"), -contains("Grade[c]" ),
         contains("APValue"))  %>% 
  transmute(A = rowSums(. == "A"), B = rowSums(. == "B"), 
            C = rowSums(. == "C"), D = rowSums(. == "D"), 
            No.grade = rowSums(.=="-"), APvalue.001 = rowSums(. <= "0.001"))

# add this count into original strucutes
lipidSelect <- lipidomics %>% bind_cols(lipidCount)

# Filter the dataset based on your criteria  
message("Please note the file is filtered by three standards. For same lipidmolecule: \n 1. Rej (rejection identification) =0; 2. at least k number of Grade B; 3. there are at least 4 p value less or equal than 0.001.\n The filtered data is stored in the filtered.data.csv.")
k <- readline("Please type the number of at least B grade you want, e.g. 4: ") %>% as.numeric(.)
j <- readline("Please type the number of at least p values less or equal than 0.001 you want, e.g. 4: ") %>% as.numeric(.)
filtered_lipidomics <- lipidSelect %>% 
  rowwise() %>% 
  filter( Rej == 0 & sum(A, B) >= k & APvalue.001 >= j)

# store the filtered data into the filtered.data.csv file  
message("Please note that the filtered data are stored in filtered.data.csv.")
write.csv(filtered_lipidomics, "filtered.data.csv")

# function to help finding the saturation pattern and counts. 
# SFA pattern is defined as ":0", MUFA is defined as ":1" 
# and PUFA is defined as ":[2-9]" (colon followed by any number from 2 to 9)
message("Please note that in the LipidMolec column, \n Pattern of SFA is defined as *:0 (colon followed by 0)\n MUFA is defined as *:1 (colon followed by) \n PUFA is defined as *:[2-9] (colon followed by any number from ranges of 2-9)")
CountPatternByRow <- function(x){
  pattern_name <- i <- j <- k <- c()
  i <- str_count(x, ":0")
  j <- str_count(x, ":1")
  k <- str_count(x, ":[2-9]")
  SFA <- paste(rep("SFA", i), collapse = "/")
  MUFA <- paste(rep("MUFA", j), collapse = "/")
  PUFA <- paste(rep("PUFA", k), collapse = "/")
  pattern_name <- paste( SFA, MUFA, PUFA, sep = "/")
  patterns <- data.frame(pattern= pattern_name, SFA=i, MUFA=j, PUFA=k, stringsAsFactors = FALSE) %>% as.matrix(.)
  return(patterns)
}

# make a data store the pattern and count information
lipid_list <- sapply(filtered_lipidomics$LipidMolec, function(x) CountPatternByRow(x)) 
lipid_list <- t(lipid_list) %>% data.frame(., stringsAsFactors = FALSE)
# name the pattern data
colnames(lipid_list) <- c("FA.name", "SFA", "MUFA", "PUFA")

# reformat the FA.name style by deleting extra speration mark "/"
message("Please note that any lipid molecule pattern which are not from the SFA, MUFA, PUFA are defined as None, e.g Q10")
lipid_list$FA.name <- apply(lipid_list, 1, function(x)x[1] <- x[1] %>% str_replace(., "//", "/") %>% str_remove(., "^/") %>% str_remove(., "/$") )
# assign the other pattern as None, e.g. Q10
lipid_list$FA.name[lipid_list$FA.name==""] <- "None"

# reorder the column position and put the counting patterns in between FA and FA Group key columns
count_lipid <- filtered_lipidomics %>% select(1:4) %>% cbind(., lipid_list)
count_lipid <- count_lipid %>% cbind(., filtered_lipidomics[5:ncol(filtered_lipidomics)]) 
rownames(count_lipid) <- NULL
# write the count of pattern into count_lipid.csv file. 
message("Please note the file contains the count for pattern SFA, MUFA and PUFA are stored in the count_lipid.csv")
write.csv(count_lipid, "count_lipid.csv")

# select columns of information for calculating the aggregation of MainArea of samples
selected_lipids <- count_lipid %>% select(Class,  FA.name, SFA, MUFA, PUFA, contains("MainArea"))
# transform attributes of SFA, MUFA, PUFA for calculations
names <- c("SFA", "MUFA", "PUFA")
DataAttribute <- function(x){class(x) <- as.numeric(x)}
transformed_lipid <- selected_lipids %>% mutate_at(names, DataAttribute)

#calculate the aggregation of lipid by same class and FA.name
aggregate.lipid <- transformed_lipid %>% group_by(Class, FA.name) %>% summarise_all(.funs = sum)
# write the aggregation information into aggregated.csv file
message("Please note that the aggregated csv file will be stored in aggregated.csv")
aggregate.lipid %>% arrange(Class, FA.name) %>% write.csv(., "aggregated.csv")







