####################################################################################
# Script: fattyAcidsSaturation_analysis.2.2.3.r
# Author: Wenting Lyu
# Notes: This script helps calculate the 
#        SFA, MUFA, PUFA and the aggregated main area for each sample.
#       First, Make sure that your R and Rstudio are newly enough for installing the 
#             packages needed in the script. Otherwise the script will pop out warnings 
#             for packages and won't run.
#       Second, please set the working environment first. Users can copy the project and
#               put it in the directory with the scripts. After that please click the
#               project first and then run the script.
#       Third, to run the script, please type the command below in the console:
#                 source("fattyAcidsSaturation_analysis2.2.3.r")   
#              or click the button "source"
#         
#         
#####################################################################################
rm(list=ls())
source("fattyAcidsSaturation_analysis.FUNCTIONS.2.2.3.r")

# Check directory existence, if not then make one
# all the plots will stored in plot directory and data in the data directory
dirs <- c("data", "plot")
mkdirs(dirs)
#########################################################################################
message("Please run script txt_to_csv.R for converting original file from LipidSearch to get standard file for analysis. \n If you already have file generated by this script, you can continue. ")
############################################################################################ 
# filter data 
# Read in file, and store the data 
message("Please open the standand file generated from txt_to_csv.R")
lipidomics <- read_csv(file.choose("Please open the standard file"), col_types = cols())

# select and count the sample grades you want, filter the p value which less than 0.001
# this step extract the needed sample information from the file automatically
lipidCount <- lipidomics %>% 
  select(contains("Grade"), -contains("Grade[c]" ),
         contains("APValue"))  %>% 
  transmute(A = rowSums(. == "A"), B = rowSums(. == "B"), 
            C = rowSums(. == "C"), D = rowSums(. == "D"), 
            Invalid.grade = rowSums(.=="-"), APvalue.001 = rowSums(. <= "0.001"))

# add this count into original strucutes
lipidSelect <- lipidomics %>% bind_cols(lipidCount)

# Filter the dataset based on your criteria  
message("Please note the file is filtered by three standards. For same lipidmolecule: \n 1. Rej (rejection identification) =0; 2. at least group_info number of Grade B; 3. there are at least 4 p value less or equal than 0.001.\n The filtered data is stored in the filtered.data.csv.")
k <- readline("Please type the number of at least B grade you want, e.g. 4: ") %>% as.numeric(.)
j <- readline("Please type the number of at least p values less or equal than 0.001 you want, e.g. 4: ") %>% as.numeric(.)
filtered_lipidomics <- lipidSelect %>% 
  rowwise() %>% 
  filter( Rej == 0 & sum(A, B) >= k & APvalue.001 >= j)

# store the filtered data into the filtered.data.csv file  
message("Please note that the filtered data are stored in filtered.data.csv.")
write.csv(filtered_lipidomics, "data/filtered.data.csv")



# input the group information and reterieve the data from the csv file.
samples <- Input(filtered_lipidomics)
# sample info
sample_info <- samples[[1]]
# group name info
group_names <- samples[[2]]
# group number info
ngroups <- samples[[3]]

# retrieve the group and its samples information
info_list <- RetrieveInfo(sample_info)
repeats <- info_list[[1]]
sample_list <- info_list[[2]]


# make a data store the pattern and count information
lipid_list <- sapply(filtered_lipidomics$LipidMolec, function(x) CountPatternByRow(x)) 
lipid_list <- t(lipid_list) %>% data.frame(., stringsAsFactors = FALSE)
# name the pattern data
colnames(lipid_list) <- c("FA_types", "SFA", "MUFA", "PUFA")

# reformat the FA_types style by deleting extra speration mark "/"
message("Please note that any lipid molecule pattern which are not from the SFA, MUFA, PUFA are defined as None, e.g Q10")
lipid_list$FA_types <- apply(lipid_list, 1, function(x)x[1] <- x[1] %>% str_replace(., "//", "/") %>% str_remove(., "^/") %>% str_remove(., "/$") )
# assign the other pattern as None, e.g. Q10
lipid_list$FA_types[lipid_list$FA_types==""] <- "None"

# reorder the column position and put the counting patterns in between FA and FA Group key columns
count_lipid <- filtered_lipidomics %>% select(1:4) %>% cbind(., lipid_list)
count_lipid <- count_lipid %>% cbind(., filtered_lipidomics[5:ncol(filtered_lipidomics)]) 
rownames(count_lipid) <- NULL
# write the count of pattern into count_lipid.csv file. 
message("Please note the file contains the count for pattern SFA, MUFA and PUFA are stored in the count_lipid.csv")
write.csv(count_lipid, "data/count_lipid.csv")

# select columns of information for calculating the aggregation of MainArea of samples
selected_lipids <- count_lipid %>% 
  select(Class,  FA_types, SFA, MUFA, PUFA, contains("MainArea"))

# transform attributes of SFA, MUFA, PUFA for calculations
names <- c("SFA", "MUFA", "PUFA")
DataAttribute <- function(x){class(x) <- as.numeric(x)}
transformed_lipid <- selected_lipids %>% mutate_at(names, DataAttribute)

#calculate the aggregation of lipid by same class and FA_types
aggregate_lipids <- transformed_lipid %>% group_by(Class, FA_types) %>% summarise_all(list(sum))
observation_count <- transformed_lipid %>% group_by(Class, FA_types) %>% tally()
aggregate_lipids <- left_join(aggregate_lipids, observation_count) 
aggregate_lipids <- aggregate_lipids %>% select(Class, n, FA_types, SFA, MUFA, PUFA, sample_list)

# write the aggregation information into aggregated.csv file
message("Please note that the aggregated csv file will be stored in aggregated.csv")
aggregate_lipids %>% arrange(Class, FA_types) %>% write.csv(., "data/aggregated.csv")

# select three variables Class, n, FA_types for analysis
group_lipids <- aggregate_lipids %>% select(Class, n, FA_types)

# make a data frame contains sample information and group information
group_info <- data.frame(samples=sample_list, groups=repeats, 
                         stringsAsFactors = FALSE) %>% 
  group_by(groups) 

# calculate the SFA, MUFA and PUFA's percentages 
fa_percent <- group_lipids %>% rowwise() %>% 
  # calculate how many SFA, MUFA and PUFA by row (by different SFA, MUFA and PUFA combination patterns)
  mutate(SFA = str_count(FA_types, "SFA"),
         MUFA= str_count(FA_types, "MUFA"), 
         PUFA= str_count(FA_types, "PUFA"), ) %>%   
  # calcutate SFA, MUFA and PUFA's percentage by row
  mutate("%SFA" = SFA/(SFA+ MUFA + PUFA), 
         "%MUFA" = MUFA/(SFA+ MUFA + PUFA), 
         "%PUFA"= PUFA/(SFA+ MUFA + PUFA)) 

# combine the percentage information with aggregated lipid info
fa_percent <- aggregate_lipids %>% ungroup() %>% select(sample_list) %>% cbind(fa_percent, .)



# find median and mean for each sample in each group and calculate its value
data <- CalcGroup( fa_percent, group_info)
write.csv(data, "data/mean_median.csv")

# reformat the data
dt_mean <- FormatData(data, "mean")
dt_sd <- FormatData(data, "sd")
dt <- left_join(dt_mean, dt_sd, by = c("Class", "TYPE", "Groups"))
dt_median <- FormatData(data, "median")

# stack plots based on mean
pars1 <- c("Groups", "mean", "TYPE")
p1 <- PlotTypes(dt, pars1) + 
  labs(title = "mean based stackplot") + 
  geom_bar(stat = "identity") + 
  facet_wrap(~Class, scales = "free") +
  scale_y_continuous(labels = scientific)
print(p1)
ggsave(filename = "meanBased.stackplots.png", path="plot/", device="png")

# stack plots based on median
pars2 <- c("Groups", "median", "TYPE")
p2 <- PlotTypes(dt_median, pars2) + 
  labs(title = "median based stackplot") + 
  geom_bar(stat = "identity") +
  facet_wrap(~Class, scales = "free") +
  scale_y_continuous(labels = scientific)
print(p2)
ggsave(filename = "medianBased.stackplots.png", path="plot/", device="png")

# bar plots split by lipid class
pars3 <- c("TYPE", "mean", "Groups")
p3 <- PlotTypes(dt, pars3)  +  
  geom_bar(stat = "identity",  position=position_dodge()) +
  geom_errorbar(aes(ymin=mean, ymax=mean+sd), width=.1,
                position=position_dodge(.9)) +
  facet_wrap(~Class, scales = "free") +
  scale_y_continuous(labels = scientific)
print(p3)
ggsave(filename = "meanBased.fattyAcids.png", path="plot/", device="png")

# normalized the data for visualization
dt_norm<- FoldChange(dt)
p4 <- PlotTypes(dt_norm, pars3)  +  
  geom_bar(stat = "identity",  position=position_dodge()) +
  facet_wrap(~Class, scales = "free") +
  labs(x = "Fatty Acids types", y = "fold change", title = "Fold Change plots")
print(p4)
ggsave(filename = "meanBased.foldchange.png", path="plot/", device="png")


# percentage plots
p5 <- PlotTypes(dt, pars1) + labs(title = "mean based stackplot") + 
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Class, scales = "free") 
print(p5)
ggsave(filename = "percentage.png", path="plot/", device = "png")


# boxplot
# reformat data
dp <- data %>% select(Class, contains("MainArea")) 
rownames(dp) <- dp$Class
dp2 <- rbind(dp[,-1], Groups= rep(group_info$groups, 3))
dp3 <- dp2 %>% t() %>% data.frame(., stringsAsFactors = FALSE) 
dp3 <- dp3 %>% cbind(pattern = colnames(dp2), .) %>% data.frame(stringsAsFactors = FALSE) %>% 
  mutate_at(vars(pattern), list(~str_remove_all(., ".*_")))
dp4 <- dp3 %>% gather("class", "value", -c(Groups, pattern)) %>% mutate_at(vars(value), DataAttribute)


pars4 <- c("pattern", "value", "Groups")
p6 <- PlotTypes(dp4, pars4) + 
  geom_boxplot( width = 0.5, size = 0.4,
                position = position_dodge(0.8),
                alpha = 0.4) +
  geom_dotplot(
    #trim = FALSE,
    binaxis='y', stackdir='center', dotsize = 0.6,
    position = position_dodge(0.8),
    alpha = 0.8) +
  facet_wrap(~class, scales = "free")+
  scale_y_continuous(labels = scientific) +
  labs(x = "Fatty Acids types", y = "AUC", title = "boxplots")

print(p6)
ggsave(filename = "FA_boxplot.png", path="plot/", device = "png")


