####################################################################################
# Script: txt_to_csv.2.R
# Author: Wenting Lyu
# Notes: this script helps transform the txt file to cxv file for later analysis.
#         please note that there are two ways to run the script.
#         1) interactive way. 
#         First, run script in console by typing: source("txt_to_csv.R") 
#         Second, select the txt file generated by lipidSearch from the poping window
#         Third, input the name for storing the uncleaned data, e.g. "uncleanedData.csv"
#         2) straight way.
#         First comment the interactive way by selecting the interactive block in the code 
#               (comment shortcut: command+shift+c)
#         Second rewrite the last line of code write_csv(., name) by changing the name variable 
#               to the name you want, e.g. "uncleanedData.csv"
#         Third run the code line by line or as a whole
#####################################################################################
rm(list=ls())

list.of.packages <- c("tidyverse", "readr", "magrittr")
need.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if(length(need.packages)) install.packages(need.packages)


# Suppress the package messages
lapply(list.of.packages, function(x) 
  suppressMessages(require(x, character.only = TRUE, quietly = TRUE)))

files <- read_table(file.choose(), skip_empty_rows = TRUE)


index <- sapply(files, function(x) which(str_detect(x, "Result"))) + 1
contents <- files %>% filter(row_number() >= index)

# convert data format into data.frame
data <- apply(contents, 1, function(x)str_split(x, "\t") %>% unlist) %>% t() %>% as.data.frame()
colnames(data) <- unlist(data[1, ])
data <- data[-1, ]

sample.neg <- sapply(files, function(x) length(which(str_detect(x, "neg"))))
sample.pos <- sapply(files, function(x) length(which(str_detect(x, "pos"))))

# Verify the sample size info are correct.
message("Reminder: Is your sample negative tests are ", sample.neg, " times?")
message("Reminder: Is your sample positive tests are ", sample.pos, " times?")


# reconstruct the data columns and store it into the file
####################################################################################
# Interactive way to generating file by just typing the command: "source("txt_to_csv.R")", 

message("Please input the name for the uncleaned data, e.g. uncleanedData.csv")
name <- readline("File name: ")

# selecting the columns we want for analysis
cols.data <- data %>%
  select(contains("ARatio"), contains("APValue"), contains("MainIon"),
         contains("MainGrade"), contains("MainArea"),
         -contains("NMA"), -contains("Score")
  )
unorder.name <- paste("unordered.", name, sep="")
#### unordered data            
uncleaned.data <- data %>% select(1:9) %>% bind_cols(cols.data) %>% write_csv(., unorder.name)

#### ordered ones 
order.sample.names <- uncleaned.data %>% 
  select(matches("\\[(c|s.*)\\]")) %>%    
  colnames() %>% 
  str_sort(., numeric=TRUE) 

unorder.data <- uncleaned.data[-which(names(uncleaned.data) %in% order.sample.names)]

order.data <- uncleaned.data[,order.sample.names] %>% 
  bind_cols(unorder.data, .) %>%
  arrange(Class, LipidMolec) %>% 
  write_csv(., name)
